openapi: 3.1.0
info:
  title: Simple API
  description: A basic OpenAPI description with a single endpoint.
  version: 1.0.0
paths: {}
servers:
  - url: 'http://api-test-tunnel.local'
    description: Local development server
